README.md, docs/PERSONAS.md
Describe how the working group fits in to the list of personas, and which function we aim to improve.
Also, add list of active documents to the README.
@SteveLasker - I think this language might addresses some of the points you raised in #3.
cc @nishakm
=> Which persona are we designing around?

README.md, docs/REQUIREMENTS.md
~~Still need to iron out with the WG what to put in each section. Broken down into the following categories:~~
~~- MUST have~~
~~- SHOULD have~~
~~- Nice to have~~
See https://github.com/opencontainers/wg-reference-types/pull/7#issuecomment-1030339073
=> Add initial requirements doc (placeholder)

README.md, docs/TEMPLATE.md
As discussed in this week's meeting, add a template for people to use to submit proposals so that they are more accessible for people to compare.
=> Add template for proposals

GOVERNANCE.md, README.md
Signed-off-by: Nisha K <nishak@vmware.com>
=> Add initial governance document

README.md, docs/RUBRIC.md
=> Add rubric for proposal evaluation

minutes/2022-03-08.md
=> Minutes for March 8 2022

README.md, docs/proposals/PROPOSAL_C.md
=> Add Proposal C

docs/REQUIREMENTS.md
During the group's first attempt at evaluating a proposal, there
were different interpretations of the filtering user stories.
Hopefully these adjustments would make them more clear.
=> Make filtering user stories more clear

minutes/2022-03-15.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
=> Add 2022-03-15 minutes

minutes/2022-03-22.md
=> Minutes for 2022-03-22

README.md
=> Fix links for meeting agenda and notes

minutes/2022-03-29.md
Adding minutes for 2022-03-29.
=> Minutes for 2022-03-29

README.md, docs/proposals/PROPOSAL_A.md
This proposal defines a new artifact manifest and corresponding referrers extension API for registries to support reference types.
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
=> Proposal A - Artifact Manifest

docs/REQUIREMENTS.md
A few small fixes so my linter doesn't complain about this file.
=> Linting and typo fixes for the requirements

docs/TEMPLATE.md
This updates the template with a requirements section.
=> Add requirements to the template

README.md, docs/proposals/PROPOSAL_E.md
This is cherry picks from A, B, and D to create a proposal that works with existing registries while allowing an upgrade path with a value add from that upgrade (more efficient queries and minimal artifacts).
=> Adding proposal E

minutes/2022-04-05.md, minutes/2022-04-12.md, minutes/2022-04-19.md, minutes/2022-04-26.md, minutes/2022-05-03.md
=> Add minutes for April and May 3rd

docs/proposals/PROPOSAL_D.md
This extends proposal D with how various requirements are handled by the proposal.
=> Adding requirements to Proposal D

docs/UPGRADING.md
Added a matrix of various scenarios with producers, registries, and consumers at various stages.
... with some help from @sudo-bmitch  !
=> Add Proposal E upgrade scenarios

docs/proposals/PROPOSAL_B.md
Use real mediatypes to more accurately describe the proposed changes. Resolves #40
=> Clarify mediatypes used in Proposal B

docs/proposals/PROPOSAL_F.md
I believe this more accurately reflects Proposal F's handling of the requirements.
=> Updating requirements for Proposal F

README.md
Add links to the README to indicate location of PR changes
=> Add links to in-progress upstream PR changes

docs/proposals/PROPOSAL_E.md
This pulls up some of the concepts from the requirements into the proposal itself. In particular, the registry section has been expanded with an explanation of garbage collection expectations, and client workflows have been described.
=> Clarify registry and client expectations in proposal E

docs/proposals/PROPOSAL_E.md
This PR looks at what would happen if we switched to a single digest tag without the hash that gives us idempotent updates.
Con:
- We introduce race conditions
- Adding artifacts pushes more work to the client to update the index
- The state of the index depends on the last client pushing it, so a bad client, or a client that isn't aware of newer extensions added to the index, could delete data from previous artifact pushes
- Referrers cannot be updated if immutable tags are used
Pro:
- Pulls are much more efficient and follow the same logic as the API
Voting for this option is happening in #65.
=> Switch to a single digest tag

README.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
cc @sudo-bmitch @jdolitsky
=> Update readme for archive
